language: python
python: "3.5"
sudo: required
 
before_install:
  - sudo apt-get install -qq -y python3-numpy
  - sudo apt-get install -qq -y python3-scipy
  - sudo apt-get install -qq -y python3-matplotlib

install:
  - pip install numpy
  - pip install scipy


script: nosetests