language: python
python:
  - "3.5"

# 执行安装前安装必要的依赖环境
before_install:
  - sudo apt-get install python3-numpy --yes
  - sudo apt-get install python3-scipy --yes
  - sudo apt-get install python3-matplotlib --yes

install:
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt --use-mirrors

script: nosetests