language: python
sudo: required
install: true
python:
  - "3.5"

before_install:
  - "apt-get install python3-numpy --yes"
  - "apt-get install python3-scipy --yes"
  - "apt-get install python3-matplotlib --yes"

install:
  - "pip install numpy"
  - "pip install scipy"


script: nosetests