language: python
dist: trusty
sudo: required

python:
    - "3.5"

before_install:
    - sudo apt-get install -y python3-dev
    - sudo apt-get install -y python3-numpy
    - sudo apt-get install -y python3-scipy
    - python -m pip install scipy
    - sudo apt-get install -y python3-matplotlib
    - sudo apt-get install -y libasound-dev
    - wget http://portaudio.com/archives/pa_stable_v19_20140130.tgz
    - tar -zxvf pa_stable_v19_20140130.tgz
    - cd portaudio/
    - ./configure && make
    - sudo make install
    - cd ..
    - sudo apt-get install -y python3-pyaudio
    - python -m pip -V
    - python -m pip install matplotlib
    - python -m pip install pyaudio
    - python -m pip install nose
    - sudo apt-get install -y libcurl4-gnutls-dev
    - sudo apt-get install -y python3-pycurl
    - sudo apt-get install -y python3-pycurl-dbg
    - python -m pip install pycurl
#    - pip uninstall -y pycurl
#    - pip install pycurl

install:
    - python -m pip install -r requirements.txt --timeout 600

script: python -m nose -s

notifications:
    email: false
