language: python
dist: trusty
sudo: required

python:
    - "3.5"

before_install:
    - sudo apt-get install -y python3-dev
    - sudo apt-get install -y python3-numpy
    - sudo apt-get install -y python3-scipy
    - sudo apt-get install -y python3-pyaudio

install:
    - pip install -r requirements.txt --timeout 600

script: nosetests -s

notifications:
    email: false
