guage: python
python:
    - "3.5"
before_install:
    - sudo apt-get install python3-dev
    - sudo apt-get install python3-numpy
    - sudo apt-get install python3-scipy
    - sudo apt-get install python3-matplotlib
install:
    - pip install numpy
    - pip install scipy
    - pip install -r requirement.txt
script: nosetests -s
